trigger:
  - main

pool:
  vmImage: 'Ubuntu-Latest'

variables:
  PHP_VERSION: '8.0.2'
  PHPUNIT_VERSION: '9.5.10'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- script: |
    sudo apt-get update
    sudo apt-get install -y php${{ variables.PHP_VERSION }} php${{ variables.PHP_VERSION }}-cli php${{ variables.PHP_VERSION }}-mbstring unzip
    curl -sS https://getcomposer.org/installer -o composer-setup.php
    sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    sudo composer global require "phpunit/phpunit:${{ variables.PHPUNIT_VERSION }}"
    sudo ln -s /root/.composer/vendor/bin/phpunit /usr/local/bin/phpunit
  displayName: 'Install PHP and Composer'

- script: |
    sudo apt-get install -y git
    git clone https://github.com/{your-repository}.git
    cd {your-repository}
    composer install
  displayName: 'Clone and install dependencies'

- script: |
    phpunit
  displayName: 'Run PHPUnit tests'